### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by frustreated** [stereomatchingkiss/QRenamer#1]
very interesting with this but issues are as following 
RCC: Error in 'pics.qrc': Cannot find file 'pics/add.png'
RCC: Error in 'pics.qrc': Cannot find file 'pics/delete.png'
RCC: Error in 'pics.qrc': Cannot find file 'pics/folder.png'
RCC: Error in 'pics.qrc': Cannot find file 'pics/clipboard_empty.png'
RCC: Error in 'pics.qrc': Cannot find file 'pics/folders_explorer.png'
...............

**Comment by stereomatchingkiss** [comment]
Hi, as the readme.txt said

You can download the icons use by this app from 
https://mega.nz/#!UslFiYQJ!-eNluUhjH5S2XBlpep5RdZZ8aGYJwqgWDBXvxh5dmOA
and place it in the pics folder, this way the Qt resource
system should be able to find the pics

**Comment by frustreated** [comment]
thanks for your ans;
project often requested rushed and finished timeless.
if any possible , we could put this forward.
every one may need this.
i like it~

**Comment by stereomatchingkiss** [comment]
Hello, @frustreated 
Thanks, I am glad you like it.

>if any possible , we could put this forward.

I am happy to hear this, if you have any features request, found some bugs, please open a new issues. I will try my best to solve them.
